#!/bin/bash
#Author:ABS
#Date:Sep-07-2020
#Discription:Create user and group

echo "\n*****Creat user and group*****\n"

sleep 3

groupadd admin
useradd u2082020
groupadd family
useradd abie -g family
yum install wget finger httpd -y
~
